server:
  port: 8080
  servlet:
    context-path: /
spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9200
      cluster-name: elasticsearch
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password:
    jedis:
      pool:
        max-active: 50
        min-idel: 20
  datasource:
    #    驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

#控制台打印sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

      
