server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    #    驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  #使用NacosRule配合集群模式优先选择同集群的规则
#控制台打印sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
feign:
  client:
    config:
      default: #default表示所有feign服务都用如下配置，如果需要指定服务，则替换成服务名称即可
        loggerLevel: BASIC  #默认只需要BASIC级别或者NONE级别的日志
  httpclient:
    enabled: true  #是否开始连接池
    max-connections: 200  #最大连接数
    max-connections-per-route: 50  #每个路径最大的连接数

